"""Initial

Revision ID: 73540575ac26
Revises: 
Create Date: 2026-04-14 15:07:37.153635

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73540575ac26'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kb_entries',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('attack_class', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('template', sa.String(), nullable=False),
    sa.Column('tags', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prompt_variants',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('scan_run_id', sa.String(), nullable=False),
    sa.Column('parent_id', sa.String(), nullable=True),
    sa.Column('attack_class', sa.String(), nullable=False),
    sa.Column('strategy_applied', sa.String(), nullable=True),
    sa.Column('depth', sa.Integer(), nullable=True),
    sa.Column('prompt_text', sa.String(), nullable=False),
    sa.Column('response_text', sa.String(), nullable=True),
    sa.Column('verdict', sa.String(), nullable=False),
    sa.Column('deterministic_matches', sa.String(), nullable=True),
    sa.Column('semantic_classification', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scan_runs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tllm_profile_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('attack_classes', sa.String(), nullable=False),
    sa.Column('mutation_strategies', sa.String(), nullable=False),
    sa.Column('mutation_depth', sa.Integer(), nullable=True),
    sa.Column('total_prompts_sent', sa.Integer(), nullable=True),
    sa.Column('vulnerabilities_found', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tllm_profiles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('endpoint_url', sa.String(), nullable=True),
    sa.Column('api_key_ref', sa.String(), nullable=True),
    sa.Column('system_prompt', sa.String(), nullable=True),
    sa.Column('has_rag', sa.Boolean(), nullable=True),
    sa.Column('accepts_documents', sa.Boolean(), nullable=True),
    sa.Column('accepts_multimodal', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tllm_profiles')
    op.drop_table('scan_runs')
    op.drop_table('prompt_variants')
    op.drop_table('kb_entries')
    # ### end Alembic commands ###
